### ISSUE TITLE
Не сразу обновляется страница, которая подключена через include

### ISSUE THREAD

**Issue by kashaeva-dev** [MrDave/StaticJinjaPlus#11]

**Comment by SGKespace** [comment]
**Вводные:**
card.html - шаблон карточки 
index.html с шаблоном Jinja2  `{% include "card.html" %}`
запускаем используя ключ
` -w, --watch        Render the site, and re-render on changes to <srcpath>`
следующим образом
`python3 main.py -w`

**Проблема:**
Меняем что-то в  card.html  -  прога это видит, даже в /build выкладывает измененный  card.html, но т.к. файл где прописан include не менялся, то он не рендерится и все остается как есть. Таким образом до тех пор, пока index.html не изменится из card.html  в обработанный файл /build/index.html ничего не попадет.

**Comment by SGKespace** [comment]
Решение:
Объявляем card.html частичным - делаем префикс "_" :  _card.html, тогда запись будет 
`{% include "_card.html" %}`
Это приведет к тому, что _card.html  отрендерится но не перенесется в /build, а index.html изменится и отрендерится.
